# Site settings
title: ZhaoZhixuan's website
email: zhaozhixuan97@gmail.com
url: https://github.com/zhaozhixuan97
description: "Welcome to my personal website. I would like to share my researches, learning processes, and interested paper on this website."
keywords: "Electronics Science and Engineering, Mechanical Manufacturing and Automation"
skills: "Electronics Science and Engineering, Mechanical Manufacturing and Automation"
meta_author: Zhixuan Zhao

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4169e1 #80B3FF
  primary-rgb: "65,105,225" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: MEng. Zhixuan Zhao
  location: Location
  social: Around the Web
  credits: Announcement

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/zzxlovexiao
  - title: facebook
    url:
  - title: researchgate
    url: https://www.researchgate.net/profile/Zhao-Zhixuan-2
  - title: linkedin
    url: https://www.linkedin.cn/incareer/jobs
  - title: github
    url: http://github.com/zhaozx97

# Postal address (add as many lines as necessary)
address:
  - line: Northwestern Polytechnical University
  - line: Youxi Road, Xi'an, Shaan Xi, China

# Credits content
credits: 'I am now looking for a PhD position. If you are interested in my background and research experience, feel free to contact me at any time.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
